n1=int(input("Primer numerador = "))
d1=int(input("Primer denominador = "))
n2=int(input("Segundo numerador = "))
d2=int(input("Segundo denominador = "))
print(n1,"/",d1," , ",n2,"/",d2)
s=float(n1/d1+n2/d2)
r=float(n1/d1-n2/d2)
m=float((n1/d1)*(n2/d2))
d=float((n1/d1)/(n2/d2))
print("La suma es igual a: ",s)
print("La resta es igual a: ",r)
print("La multiplicación es igual a: ",m)
print("La división es igual a: ",d)
